# Generated by Django 3.0.3 on 2020-04-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BRDDesc',
            field=models.TextField(blank=True, null=True, verbose_name='brand description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='BRDName',
            field=models.CharField(max_length=40, verbose_name='brand name'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VarDesc',
            field=models.TextField(blank=True, null=True, verbose_name='variant description'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VarName',
            field=models.CharField(max_length=40, verbose_name='variant name'),
        ),
    ]
