# Generated by Django 3.0.3 on 2020-04-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName', models.CharField(max_length=200, verbose_name='product Name')),
                ('proDesc', models.TextField(verbose_name='product Description')),
                ('proPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product price')),
                ('proCost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product Cost')),
                ('proCreated', models.DateTimeField(verbose_name='product Created')),
            ],
        ),
    ]
