# Generated by Django 3.0.3 on 2020-04-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productimag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimag',
            name='PRDIImag',
            field=models.ImageField(upload_to='Porduct/', verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatMain_Category', models.CharField(max_length=50)),
                ('CatDesc', models.TextField()),
                ('CatImage_Category', models.ImageField(upload_to='category/')),
                ('CatParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Category')),
            ],
        ),
    ]
