# Generated by Django 3.0.3 on 2020-04-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20200413_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category ', 'verbose_name_plural': 'Categores '},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products '},
        ),
        migrations.AlterModelOptions(
            name='productimag',
            options={'verbose_name': 'ProductImag ', 'verbose_name_plural': 'ProductImages '},
        ),
        migrations.AlterField(
            model_name='category',
            name='CatDesc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CatImage_Category',
            field=models.ImageField(upload_to='category/', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CatMain_Category',
            field=models.CharField(max_length=50, verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CatParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CatParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Category', verbose_name='Category Parent'),
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALNAlternative', models.ManyToManyField(related_name='alternative_product', to='ecommerce.Product')),
                ('PALNProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_Product', to='ecommerce.Product')),
            ],
            options={
                'verbose_name': 'Product_Alternative ',
                'verbose_name_plural': 'Product_Alternatives',
            },
        ),
    ]
