# Generated by Django 3.0.3 on 2020-04-16 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20200415_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CatImage_Category',
            field=models.ImageField(upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALNAlternative',
            field=models.ManyToManyField(related_name='alternative_product', to='ecommerce.Product', verbose_name='alternative'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALNProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_Product', to='ecommerce.Product', verbose_name='product'),
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCAccessories', models.ManyToManyField(related_name='accessories_product', to='ecommerce.Product', verbose_name='accessories')),
                ('PACCproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_Product', to='ecommerce.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product_Accessory ',
                'verbose_name_plural': 'Product_Accessories',
            },
        ),
    ]
