# Generated by Django 3.0.3 on 2020-04-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
        ('ecommerce', '0006_auto_20200416_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='proCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Category'),
        ),
    ]
