# Generated by Django 3.0.3 on 2020-04-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20200419_0307'),
        ('ecommerce', '0007_auto_20200417_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proIImag',
            field=models.ImageField(blank=True, null=True, upload_to='Porduct/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.Brand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Category', verbose_name='category'),
        ),
    ]
