# Generated by Django 3.0.3 on 2020-05-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_remove_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product_Accessories',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
