# Generated by Django 3.0.6 on 2020-05-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='C_qty',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='C_total',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Quantity'),
        ),
    ]
