# Generated by Django 3.0.6 on 2020-05-24 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_auto_20200524_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='C_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Category', verbose_name='Category'),
        ),
    ]
