# Generated by Django 3.0.6 on 2020-05-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_auto_20200524_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='C_Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product', verbose_name='prodct'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='C_total',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='total'),
        ),
    ]
