# Generated by Django 3.0.6 on 2020-05-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_auto_20200524_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='C_Product',
            field=models.IntegerField(max_length=100, verbose_name='prodct'),
        ),
    ]
