# Generated by Django 3.0.6 on 2020-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_auto_20200524_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='C_Product',
        ),
        migrations.AddField(
            model_name='cart',
            name='C_Product',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.Product', verbose_name='Product'),
        ),
    ]
