# Generated by Django 3.0.6 on 2020-06-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_auto_20200609_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
