# Generated by Django 3.0.6 on 2020-06-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
