# Generated by Django 3.0.6 on 2020-06-14 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0033_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='ipaddress')),
                ('C_StartDate', models.DateTimeField(auto_now_add=True)),
                ('C_order_date', models.DateTimeField()),
                ('C_order', models.BooleanField(default=False)),
                ('C_Products', models.ManyToManyField(to='ecommerce.CartProduct', verbose_name='Products')),
                ('C_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
