# Generated by Django 3.0.6 on 2020-06-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_cart_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proQuantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='quantity'),
        ),
    ]
