# Generated by Django 3.0.6 on 2020-06-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0035_product_proquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proQuantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
    ]
