# Generated by Django 3.0.6 on 2020-06-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_auto_20200614_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='C_ip',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='C_ip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ipaddress'),
        ),
    ]
