# Generated by Django 3.0.6 on 2020-06-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_auto_20200614_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='C_order',
            new_name='C_isorder',
        ),
    ]
