# Generated by Django 3.0.6 on 2020-06-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_auto_20200614_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='proQuantity',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='C_Quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
    ]
