# Generated by Django 3.0.6 on 2020-06-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_auto_20200614_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='C_user',
            new_name='user',
        ),
    ]
