# Generated by Django 3.0.6 on 2020-06-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_auto_20200615_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='C_isorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='C_order_date',
            field=models.DateTimeField(),
        ),
    ]
