# Generated by Django 3.0.6 on 2020-06-15 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0043_auto_20200615_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='CP_isorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
